<a href="https://colab.research.google.com/github/bhargav23/AI/blob/master/UNIT6/Cosine_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn

In [0]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [0]:
text = ['London Paris Paris', 'Paris London London']

In [0]:
cv = CountVectorizer()

In [0]:
count_matrix = cv.fit_transform(text)

In [6]:
for i in count_matrix:
  print(i)

  (0, 0)	1
  (0, 1)	2
  (0, 0)	2
  (0, 1)	1


In [7]:
count_matrix.toarray()

array([[1, 2],
       [2, 1]])

In [8]:
cosine_similarity(count_matrix)

array([[1. , 0.8],
       [0.8, 1. ]])

In [0]:
x = np.random.rand(10)*50
x = x.astype(int)
y = np.random.rand(10)*50
y = y.astype(int)

In [0]:
z = [x,y]

In [11]:
cosine_similarity([x,y])

array([[1.        , 0.82697156],
       [0.82697156, 1.        ]])

In [12]:
cosine_similarity([[2, 5], [1, 6]])

array([[1.        , 0.97690002],
       [0.97690002, 1.        ]])

In [0]:
text = ['Some Cats are bats','All bats are Cats']

In [0]:
cv = CountVectorizer()

In [0]:
count_matrix = cv.fit_transform(text)

In [16]:
count_matrix.toarray()

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0]])

In [17]:
cosine_similarity(count_matrix)

array([[1.  , 0.75],
       [0.75, 1.  ]])