<a href="https://colab.research.google.com/github/bhargav23/AI/blob/master/Lab/NumPy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. e) Matrix operations on NumPy arrays
###Practice on Python Numpy Library

* Create matrices
* Dimensions
* Modifying matrices
* Accessing elements of a matrix
* Matrix operations
* Linear algebra operations in python

## Matrices
* Rectangular arrangement of numbers in rows and columns
* Rows run horizontally and columns run vertically

### Create a matrix
* mitrix() - returns a matrix from an array type object or string of data
* Syntax: numpy.matrix(data)


In [ ]:
import numpy as np

In [ ]:
a=np.matrix("1,2,3,4;4,5,6,7;7,8,9,10")

In [ ]:
a

matrix([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [ ]:
b=np.matrix([[ 1,  2,  3,  4], [ 4,  5,  6,  7],[ 7,  8,  9, 10]])

In [ ]:
b

matrix([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

### Matrix properties
* shape( )- returns number of rows and columns from a matrix
* shape[0]- returns the number of rows
* shape[1]- returns the number of columns
* size( )- returns the number of elements from a matrix


In [ ]:
a.shape

(3, 4)

In [ ]:
a.shape[0]

3

In [ ]:
a.shape[1]

4

In [ ]:
a.size

12

### Modifying matrix using insert()

* insert- adds values at a given position and axis in a matrix
* Syntax: numpy. insert (matrix, obj,values,axis)
  * matrix - input matrix
  * obj    - index position
  * values - matrix of values to be inserted
  * axis   - axis along which values should be insert

**Adding the matrix 'col_new' as a new column to a**

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [ ]:
col_new=np.matrix("2,3,4")

In [ ]:
print(col_new)

[[2 3 4]]


In [ ]:
a=np.insert(a,0,col_new,axis=1) # axis=1 means insering the col

In [ ]:
print(a)

[[ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


**Adding the matrix ‘ row_new ’ as a new row to a**

In [ ]:
row_new = np.matrix("11,12,13,14,15")

In [ ]:
a = np.insert(a,2,row_new,axis=0) #axis = 0 means inserting the rows

In [ ]:
print(a)

[[ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [11 12 13 14 15]
 [ 4  7  8  9 10]]


### Modifying matrix using index
* Elements of matrix can be modified using index number

In [ ]:
print(a)

[[ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [11 12 13 14 15]
 [ 4  7  8  9 10]]


In [ ]:
a[1,1] = -3

In [ ]:
print(a)

[[ 2  1  2  3  4]
 [ 3 -3  5  6  7]
 [11 12 13 14 15]
 [ 4  7  8  9 10]]


### Accessing elements of matrix using index


In [ ]:
a[:1,:] #Extract elements from second row of matrix a

matrix([[2, 1, 2, 3, 4]])

In [ ]:
a[1:3,1:3]

matrix([[-3,  5],
        [12, 13]])

In [ ]:
a[:,4] #Extract elements from third column of matrix a

matrix([[ 4],
        [ 7],
        [15],
        [10]])

In [ ]:
a[1,2] #Extract element with index ( 1 ,2) from a

5


### Matrix addition
* numpy.add()- performs elementwise addition between two matrices
* Syntax: numpy.add(matrix 1,matrix 2)

**Create two matrix A and B**



In [ ]:
A = np.matrix(np.arange(0,20)).reshape(5,4)
B = np.matrix(np.arange(20,40)).reshape(5,4)

In [ ]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [ ]:
np.add(A,B)

matrix([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])


### Matrix Subtraction
* numpy.subtract()- performs elementwise subtraction between two matrices
* Syntax: numpy.subtract(matrix_1,matrix_2)



In [ ]:
np.subtract(B,A)

matrix([[20, 20, 20, 20],
        [20, 20, 20, 20],
        [20, 20, 20, 20],
        [20, 20, 20, 20],
        [20, 20, 20, 20]])


### Matrix multiplication
* numpy.dot()- performs matrix multiplication between two matrices
* Syntax: numpy.dot(matrix_1,matrix_2)





In [ ]:
#np.dot(A,B)
'''
For matrix multiplication,
number of columns in
matrix A should be equal to
number of rows in matrix B
'''

'\nFor matrix multiplication,\nnumber of columns in\nmatrix A should be equal to\nnumber of rows in matrix B\n'

In [ ]:
C = np.transpose(B)
#Transpose matrix B to make it 4 x 5 in dimension

In [ ]:
C.shape

(4, 5)

In [ ]:
np.dot(A,C)

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

### Elementwise Multiplication
* numpy.multiply() performs elementwise multiplication between two matrices
* Syntax: numpy.multiply(matrix_1,matrix_2)










In [ ]:
A.shape

(5, 4)

In [ ]:
B.shape

(5, 4)

In [ ]:
np.multiply(A,B)

matrix([[  0,  21,  44,  69],
        [ 96, 125, 156, 189],
        [224, 261, 300, 341],
        [384, 429, 476, 525],
        [576, 629, 684, 741]])

### Matrix division
* numpy.divide() performs elementwise division between two matrices
* Syntax: numpy.divide(matrix_1,matrix_2)

In [ ]:
np.divide(A,B)

matrix([[0.        , 0.04761905, 0.09090909, 0.13043478],
        [0.16666667, 0.2       , 0.23076923, 0.25925926],
        [0.28571429, 0.31034483, 0.33333333, 0.35483871],
        [0.375     , 0.39393939, 0.41176471, 0.42857143],
        [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

## Summary
  * Create matrix
  * Matrix properties
  * Modifying matrix
  * Accessing element of matrix
  * Matrix operations

### Linear algebra operations in python
  * Determinant of matrix
  * Rank of matrix
  * Inverse of matrix
  * Solving system of equations

### Determinant of matrix
* numipy. linalg.det ( ) - returns determinant of the matrix
* Syntax: numpy.linalg.det(matrix)


In [ ]:
x=np.matrix("4,5,16,7;2,-3,2,3;3,4,5,6;4,7,8,9")

In [ ]:
np.linalg.det(x)

128.00000000000009

### Rank of matrix
numpy.linalg.matrix_rank( ) - returns rank of the matrix
* Syntax: numpy.linalg.matrix_rank (matrix)



In [ ]:
x=np.matrix("4,5,16,7;2,-3,2,3;3,4,5,6;4,7,8,9")

In [ ]:
print(x)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [ ]:
rank_matrix=np.linalg.matrix_rank(x)

In [ ]:
rank_matrix

4

### Inverse of a matrix
* numpy.linalg.inv( ) - returns the multiplicative inverse of a matrix
* Syntax: numpy.linalg. inv(matrix)


In [ ]:
A=np.matrix("3,1,2;3,2,5;6,7,8")

In [ ]:
np.linalg.inv(A)

matrix([[ 0.57575758, -0.18181818, -0.03030303],
        [-0.18181818, -0.36363636,  0.27272727],
        [-0.27272727,  0.45454545, -0.09090909]])

In [ ]:
B=np.matrix("2,1,2;1,0,1;3,1,3")

In [ ]:
B.shape

(3, 3)

In [ ]:
np.linalg.inv(B)

In [ ]:
np.linalg.det(B)

### System of linear equations
* Consider a system of linear equations

> 3𝑥+𝑦+2𝑧=2

> 3𝑥+2𝑦+5𝑧=−1

> 6𝑥+7𝑦+8𝑧=3

* Now we can write the equations in the form of Ax=b


In [ ]:
A = np.matrix("3,1,2;3,2,5;6,7,8")

In [ ]:
B = np.matrix("2,-1,3").reshape(3,1)

In [ ]:
print(A)

[[3 1 2]
 [3 2 5]
 [6 7 8]]


In [ ]:
print(B)

[[ 2]
 [-1]
 [ 3]]


In [ ]:
sol_lin = np.linalg.solve(A,B)

In [ ]:
sol_lin

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])

### Summary
* Determinant of matrix
* Rank of matrix
* Inverse of matrix
* Solving system of equations